"""empty message

Revision ID: 39561cfbf89c
Revises: 4d2f530666fc
Create Date: 2014-12-22 17:07:55.389000

"""

# revision identifiers, used by Alembic.
revision = '39561cfbf89c'
down_revision = '4d2f530666fc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme_collection_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.String(length=30), nullable=False))
        batch_op.drop_column('phone')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme_collection_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=30), nullable=False))
        batch_op.drop_column('mobile')

    ### end Alembic commands ###
