"""empty message

Revision ID: 48c45a7624b9
Revises: 25f41152109a
Create Date: 2014-12-22 14:17:56.818000

"""

# revision identifiers, used by Alembic.
revision = '48c45a7624b9'
down_revision = '25f41152109a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme_collection_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=False))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme_collection_item', schema=None) as batch_op:
        batch_op.drop_column('phone')

    ### end Alembic commands ###
