"""empty message

Revision ID: 4d2f530666fc
Revises: 48c45a7624b9
Create Date: 2014-12-22 14:22:06.308000

"""

# revision identifiers, used by Alembic.
revision = '4d2f530666fc'
down_revision = '48c45a7624b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme_collection_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('psnname', sa.String(length=20), nullable=False))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme_collection_item', schema=None) as batch_op:
        batch_op.drop_column('psnname')

    ### end Alembic commands ###
